apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: schema-registry
      port: {{ .Values.schema_registry.servicePort }}
    {{- if .Values.schema_registry.prometheus.jmx.enabled }}
    - name: metrics
      port: {{ .Values.schema_registry.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ template "cp-schema-registry.name" . }}
    release: {{ .Release.Name }}
